# Generated by Django 4.2.6 on 2023-11-01 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=255)),
                ('person_saved_info', models.BooleanField(default=False)),
                ('case_officer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('current_address', models.TextField()),
                ('phone_numbers', models.CharField(max_length=200)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='uploads/personal_information/')),
                ('government_id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('government_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('saved_info', models.BooleanField(default=False)),
                ('person_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('case_type', models.CharField(blank=True, choices=[('Homicide', 'Homicide'), ('Fraud', 'Fraud'), ('Cybercrime', 'Cybercrime'), ('Sexual Assault', 'Sexual Assault')], max_length=50, null=True)),
                ('date_time_incident', models.DateTimeField(blank=True, null=True)),
                ('location_of_incident', models.CharField(blank=True, max_length=200, null=True)),
                ('reporting_party_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_party_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_party_affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('summary_of_the_case', models.TextField(blank=True, null=True)),
                ('case_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.case')),
            ],
        ),
    ]
