# Generated by Django 4.2.6 on 2023-11-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_assigncase'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_saved_info',
            field=models.BooleanField(default=False),
        ),
    ]
