# Generated by Django 4.2.6 on 2023-11-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_case_device_saved_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicdevice',
            name='connection_ports',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electronicdevice',
            name='make_and_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electronicdevice',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='electronicdevice',
            name='passwords_credentials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electronicdevice',
            name='serial_number_imei',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='electronicdevice',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
