# Generated by Django 4.2.6 on 2023-11-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_electronicdevice_connection_ports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicdevice',
            name='device_type',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('desktop_computer', 'Desktop Computer'), ('tablet', 'Tablet'), ('external_hard_drive', 'External Hard Drive'), ('usb_drive', 'USB Drive'), ('digital_camera', 'Digital Camera'), ('other', 'Other')], max_length=50),
        ),
    ]
