# Generated by Django 4.2.6 on 2023-11-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_electronicdevice_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicdevice',
            name='connection_ports',
        ),
    ]
