# Generated by Django 4.2.6 on 2023-11-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_electronicdevice_connection_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicdevice',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('Windows', 'Windows'), ('Mac', 'Mac'), ('Linux', 'Linux'), ('Andriod', 'Andriod'), ('IOS', 'IOS')], max_length=50, null=True),
        ),
    ]
