# Generated by Django 4.2.6 on 2023-12-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_delete_imageevi_remove_evidence_evidence_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case1', to='webapp.caseinfo'),
        ),
    ]
