# Generated by Django 4.2.6 on 2023-12-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_uploadedfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_closed_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='case_closed_officer',
            field=models.BooleanField(default=False),
        ),
    ]
