# Generated by Django 4.2.6 on 2024-04-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_pdfchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfchat',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
